# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

1. Import the numpy package under the name np (★☆☆)

In [ ]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

3. Create a null vector of size 10 (★☆☆)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [ ]:
arr = np.zeros((2, 8))

# get the memory size of the array
mem_size = arr.nbytes

print("Memory size of array: ", mem_size, " bytes")

Memory size of array:  128  bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a = np.random.random((3,3,3))
print(a)

[[[0.30811241 0.81133569 0.1194702 ]
  [0.72420233 0.72586089 0.25495986]
  [0.68201515 0.98473366 0.33550153]]

 [[0.49634635 0.41149374 0.46840133]
  [0.09794897 0.08598785 0.21743187]
  [0.46400554 0.7725823  0.82725924]]

 [[0.97519616 0.10430378 0.515884  ]
  [0.10599345 0.15214678 0.06360565]
  [0.41445135 0.35847268 0.73058266]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a = np.random.random((10, 10))
print(f'Minimum: {a.min()}')
print(f'Maximum: {a.max()}')

Minimum: 0.0009364116418607571
Maximum: 0.977238766498956


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.random(30)
print(f'\nMean: {a.mean()}')


Mean: 0.45716683431928834


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.zeros((10, 10))
a[0:, 0] = 1  # first row
a[0, 0:] = 1  # first column
a[0:, -1] = 1  # last row
a[-1, 0:] = 1  # last colummn
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0  # elements of (9,9) matrix in the centre = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((7,6))
a = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
print(np.diag(1 + np.arange(4),k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
tile = np.array([[1, 0], [0, 1]])
checkerboard = np.tile(tile, (4, 4))
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
matrix = np.random.rand(5, 5)
mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[-0.97451232 -1.13726696 -0.63670514 -0.37173896 -1.54894874]
 [ 0.05396886  1.16221225  1.08798264 -1.9393442  -0.53901802]
 [-1.08657349 -0.29785728  0.10097457  1.22192335  1.07978867]
 [ 0.53780123 -0.09676237  1.17058648  0.50404712  0.02994095]
 [ 0.60362267  1.19719226  1.25110942  0.55033044 -1.92275344]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
dtype_rgba = np.dtype([
    ('r', np.uint8),  # red component
    ('g', np.uint8),  # green component
    ('b', np.uint8),  # blue component
    ('a', np.uint8)   # alpha component
])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
print(np.dot(a, b))

[[1.33027835 1.42465568]
 [1.24364915 1.32308563]
 [1.56468214 1.63579276]
 [1.19876074 1.30643179]
 [0.16961356 0.18627211]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.random.random(10)
a[4:8] = - a[4:8]
print(a)

[ 0.92823924  0.67589824  0.40734595  0.50810977 -0.57819576 -0.08023839
 -0.74796804 -0.06533513  0.64708317  0.46114016]


26. What is the output of the following script? (★☆☆)
// Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: name 'Z' is not defined

28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-23-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-23-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-23-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a = np.array([-2.7, -1.5, -0.3, 0.3, 1.5, 2.7])
a_rounded = np.copysign(np.ceil(np.abs(a)), a)
print(a_rounded)

[-3. -2. -1.  1.  2.  3.]


30. How to find common values between two arrays? (★☆☆)

In [ ]:
print(np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1]))

[1 3]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2023-03-25
Today's date: 2023-03-26
Tomorrow's date: 2023-03-27


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'), np.timedelta64(1, 'D'))

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
a = np.random.rand(5) * 10
# Extract the integer part using numpy.floor()
int_part1 = np.floor(a)
print(int_part1)
# Extract the integer part using numpy.trunc()
int_part2 = np.trunc(a)
print(int_part2)
# Extract the integer part using numpy.astype()
int_part3 = a.astype(int)
print(int_part3)
# Extract the integer part using the modulo operator
int_part4 = a % 1
print(a - int_part4)
print(a)

[3. 5. 3. 0. 0.]
[3. 5. 3. 0. 0.]
[3 5 3 0 0]
[3. 5. 3. 0. 0.]
[3.51000995 5.05870451 3.11477945 0.93838008 0.34735327]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
a = np.zeros((5, 5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def my_generator():
    for i in range(10):
        yield i
a = np.fromiter(my_generator(), dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
a = linspace(0, 1, 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a = random.random(10)
print(np.sort(a))

[0.05174998 0.08430219 0.18757653 0.19029654 0.23247308 0.28365626
 0.29009654 0.54738391 0.61498858 0.81594635]


41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(np.add.reduce(a))

15


42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,7)
B = np.random.randint(0,2,7)
print(np.array_equal(A,B))

False


43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a.flags.writeable = False
a[0] = 10

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)
polar = np.column_stack((radius, angle))
print(polar)

[[0.5443097  1.00383621]
 [0.32126115 1.45627679]
 [0.54694313 0.88397813]
 [0.95799662 0.94986336]
 [0.98697927 1.10072597]
 [1.25099731 0.82132519]
 [0.5802762  1.22508957]
 [0.70618692 0.33728707]
 [0.86295418 0.89880221]
 [1.1458694  0.65488269]]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.01337093 0.0016726  0.4629062  0.32821827 0.         0.20207853
 0.07676234 0.67217422 0.03538459 0.72194416]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
coords = np.column_stack((X.ravel(), Y.ravel()))
print(coords)

[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = np.reciprocal(np.subtract.outer(X, Y))
print(C)

[[ 0  0  0]
 [ 0  0  0]
 [-1  0  0]]


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')

for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')

for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')

for dtype in [np.complex64, np.complex128]:
    info = np.finfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')

<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.uint8'>: min=0, max=255
<class 'numpy.uint16'>: min=0, max=65535
<class 'numpy.uint32'>: min=0, max=4294967295
<class 'numpy.uint64'>: min=0, max=18446744073709551615
<class 'numpy.float16'>: min=-65504.0, max=65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
<class 'numpy.complex64'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.complex128'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


49. How to print all the values of an array? (★★☆)

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
a = np.arange(20)
x = 4.443
index = np.abs(a - x).argmin()
print(a[index])

4


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
pos_color_dtype = np.dtype([('position', [('x', float), ('y', float)]),
                            ('color', [('r', int), ('g', int), ('b', int)])])

arr = np.array([((1.0, 2.0), (255, 0, 0)),
                ((3.0, 4.0), (0, 255, 0)),
                ((5.0, 6.0), (0, 0, 255))], dtype=pos_color_dtype)

print(arr)

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
a = np.random.random((100, 2))
distances = np.linalg.norm(a[:, np.newaxis, :] - a[np.newaxis, :, :], axis=-1)
print(distances)

[[0.         0.63126587 0.53862689 ... 0.87980041 0.54446003 0.49645604]
 [0.63126587 0.         0.44932313 ... 0.58562024 0.14041036 0.14216022]
 [0.53862689 0.44932313 0.         ... 0.99883986 0.50096457 0.35351132]
 ...
 [0.87980041 0.58562024 0.99883986 ... 0.         0.49824867 0.64574588]
 [0.54446003 0.14041036 0.50096457 ... 0.49824867 0.         0.14753687]
 [0.49645604 0.14216022 0.35351132 ... 0.64574588 0.14753687 0.        ]]


53. How to convert a float (32 bits) array into an integer (32 bits) in place? (★★☆)


In [ ]:
a = (np.random.rand(10)*5).astype(np.float32)
int_a = a.view(np.int32)
print(int_a)

[1065023964 1072452705 1077267894 1066299943 1075838873 1079637349
 1075884040 1061480956 1076327047 1079579796]


54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [ ]:
data = np.genfromtxt('file.csv', delimiter=',', filling_values=np.nan)

print(data)

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


56. Generate a generic 2D Gaussian-like array (★★☆)


In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
arr = np.zeros((5, 5))
p = 5
indices = np.random.randint(0, arr.size, p)
arr.flat[indices] = 1
print(arr)

[[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a = A - A.mean(axis = 1).reshape(-1, 1)
print(a)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column? (★★☆)

In [ ]:
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()])

[[5 7 9]
 [9 8 1]
 [6 2 4]]
[[6 2 4]
 [5 7 9]
 [9 8 1]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr = np.array([[1, 2, 3], [0, 0, 0], [4, 5, 6]])
# check for null columns
null_cols = np.any(arr == 0, axis=0)
print(null_cols)

[ True  True  True]


61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
def nearest_value(a, v):
    i = (np.abs(a - v).argmin())
    return a[i]
a = np.linspace(1, 10, 15)
v = 3
print(nearest_value(a, v))

2.928571428571429


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
a = np.random.random((1, 3))
b = np.random.random((3, 1))
it = np.nditer([a, b], flags=['external_loop'], op_flags=[['readonly'], ['readonly']])
sum = 0
for a, b in it:
    sum += a + b
print(sum)

[1.80472849 2.27780772 1.88156966]


63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', 'unnamed')
a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
a = np.array([1, 1, 2, 3, 3, 3, 4, 4, 5, 5])
ind = np.array([0, 2, 3, 3, 4])
np.add.at(a, ind, 1)

print(a)

[2 1 3 5 4 3 4 4 5 5]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 0, 1])
F = np.zeros(3)

np.add.at(F, I, X)

print(F)

[5. 7. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
img = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)

img_2d = img.reshape((img.shape[0] * img.shape[1], 3))

unique_colors = np.unique(img_2d, axis=0)

num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)

Number of unique colors: 9996


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr = np.random.rand(2, 3, 4, 5)

sum_last_two = np.sum(arr, axis=(-2, -1))

print(sum_last_two.shape)

(2, 3)


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [ ]:
D = np.random.rand(10)
S = np.random.randint(0, 3, size=10)

count = np.bincount(S, minlength=np.max(S)+1)
sums = np.bincount(S, weights=D, minlength=np.max(S)+1)
means = sums / count
print(means)

[0.63683268 0.37397521 0.38437833]


69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
diagonal_elements = np.diagonal(dot_product)

print(diagonal_elements)

[19 50]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
x = np.array([1, 2, 3, 4, 5])
n_zeros = 3
y = np.zeros(len(x) + (len(x) - 1) * n_zeros)
y[::n_zeros + 1] = x

print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array? (★★★)

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[1, 2]] = arr[[2, 1]]
print(arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [ ]:
triplets = np.random.randint(0, 10, size=(10, 3))
segments = set()

for triplet in triplets:
    for i in range(3):
        j = (i + 1) % 3
        segment = tuple(sorted((triplet[i], triplet[j])))
        segments.add(segment)

print(list(segments))

[(3, 4), (3, 7), (4, 6), (0, 2), (8, 9), (1, 6), (6, 8), (0, 1), (8, 8), (1, 2), (2, 7), (7, 9), (6, 7), (4, 7), (3, 8), (0, 0), (0, 3), (1, 4), (0, 6), (2, 6), (6, 6), (7, 8)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([0, 1, 2, 0, 1, 2, 2, 1, 0, 0])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 0 0 1 1 1 2 2 2]


75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
def sliding_window_array(Z, window_size):
    n_rows = len(Z) - window_size + 1
    window_view = np.lib.stride_tricks.as_strided(Z, shape=(n_rows, window_size), strides=(Z.strides[0], Z.strides[0]))
    return np.vstack(window_view)

a = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
print(sliding_window_array(a, window_size))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
a = np.random.randint(0, 2, 15)
np.logical_not(a, out = a)
a = np.random.uniform(-1.0, 1.0, 15)
np.negative(a, out = a)

array([-0.95073509,  0.93873835,  0.50791252, -0.82969845, -0.77792209,
        0.06386306,  0.90696356,  0.11507863, -0.43062395, -0.72951655,
       -0.01709014, -0.11720061, -0.98202778, -0.2063651 , -0.63430148])

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [1, 3], [3, 3]])

p = np.array([1, 2])
distances = []
for i in range(len(P0)):
    x1, y1 = P0[i]
    x2, y2 = P1[i]
    x0, y0 = p
    dist = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1) / np.sqrt((y2 - y1) ** 2 + (x2 - x1) ** 2)
    distances.append(dist)

distances = np.array(distances)
print(distances)

[2.         0.         0.70710678]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis = 1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[1.29823115e+01 2.49141856e-01 1.43313494e+00 1.00192833e+01
  2.33394412e+00 8.61436163e+00 8.60284320e-02 9.99628700e-01
  1.09917168e+01 2.93076318e-01]
 [9.12551120e+00 1.71183406e+00 5.12743524e+00 4.66222020e+00
  6.77388655e+00 3.32790918e+00 2.33719901e+00 6.01659678e+00
  5.66688082e+00 5.64887555e+00]
 [1.19585965e+01 1.46759236e+00 2.48416762e+00 9.82577731e+00
  3.22878258e+00 8.55264968e+00 1.02335747e+00 8.31954432e-01
  1.08726065e+01 4.82452866e-01]
 [1.70886284e+01 1.36812905e+00 2.50525610e+00 1.56342175e+01
  2.37275803e+00 1.41459536e+01 2.55189643e+00 4.23364564e+00
  1.65675845e+01 5.32023837e+00]
 [1.20775781e+01 3.15709184e+00 2.51739703e+00 1.25576992e+01
  2.49913406e+00 1.15186022e+01 4.40045209e+00 2.45550841e+00
  1.37411028e+01 2.25735710e+00]
 [9.25081236e+00 4.34568368e+00 5.23495108e+00 8.80378598e+00
  5.71348342e+00 7.83231132e+00 2.84626246e+00 1.01111009e+00
  1.00200523e+01 1.49509727e+00]
 [3.49708985e+00 1.02879466e+01 1.75397322e+01 7.26404022e

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [ ]:
def extract_subpart(arr, shape, center, fill_value=0):
    """
    Extracts a subpart of an array with a fixed shape and centered on a given element.
    If the subpart goes out of bounds, it is padded with the fill value.

    Parameters:
    -----------
    arr : numpy.ndarray
        The input array.
    shape : tuple of int
        The shape of the subpart to extract.
    center : tuple of int
        The coordinates of the center of the subpart to extract.
    fill_value : scalar, optional
        The value to use for padding when the subpart goes out of bounds.
        Default is 0.

    Returns:
    --------
    subpart : numpy.ndarray
        The extracted subpart of the array.
    """
    half_shape = np.array(shape) // 2
    start = np.array(center) - half_shape
    end = start + shape

    pad_start = np.maximum(0, -start)
    pad_end = np.maximum(0, end - np.array(arr.shape))

    start = np.maximum(start, 0)
    end = np.minimum(end, np.array(arr.shape))

    subpart = np.ones(shape, dtype=arr.dtype) * fill_value
    subpart[pad_start[0]:shape[0]-pad_end[0], pad_start[1]:shape[1]-pad_end[1]] = arr[start[0]:end[0], start[1]:end[1]]

    return subpart
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
print(extract_subpart(a, shape, position, fill))

[[0 0 0 0 0]
 [0 1 9 8 9]
 [0 4 0 8 6]
 [0 7 4 3 1]
 [0 3 3 2 4]]


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = np.vstack([Z[i:i + 4] for i in range(len(Z) - 3)])
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)

In [ ]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


83. How to find the most frequent value in an array?

In [ ]:
a = np.random.randint(0, 10, 20)
a = np.bincount(a).argmax()
print(a)

3


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
matrix = np.random.randint(0, 10, size=(10, 10))
block_size = 3

output_shape = (matrix.shape[0] - block_size + 1, matrix.shape[1] - block_size + 1, block_size, block_size)
strides = matrix.strides + matrix.strides
blocks = np.lib.stride_tricks.as_strided(matrix, shape=output_shape, strides=strides)

print(blocks)

[[[[8 2 3]
   [3 1 0]
   [3 1 5]]

  [[2 3 2]
   [1 0 4]
   [1 5 9]]

  [[3 2 3]
   [0 4 5]
   [5 9 3]]

  [[2 3 7]
   [4 5 7]
   [9 3 0]]

  [[3 7 4]
   [5 7 1]
   [3 0 9]]

  [[7 4 5]
   [7 1 4]
   [0 9 7]]

  [[4 5 3]
   [1 4 1]
   [9 7 7]]

  [[5 3 0]
   [4 1 5]
   [7 7 1]]]


 [[[3 1 0]
   [3 1 5]
   [6 9 4]]

  [[1 0 4]
   [1 5 9]
   [9 4 4]]

  [[0 4 5]
   [5 9 3]
   [4 4 6]]

  [[4 5 7]
   [9 3 0]
   [4 6 8]]

  [[5 7 1]
   [3 0 9]
   [6 8 2]]

  [[7 1 4]
   [0 9 7]
   [8 2 9]]

  [[1 4 1]
   [9 7 7]
   [2 9 8]]

  [[4 1 5]
   [7 7 1]
   [9 8 4]]]


 [[[3 1 5]
   [6 9 4]
   [2 3 5]]

  [[1 5 9]
   [9 4 4]
   [3 5 0]]

  [[5 9 3]
   [4 4 6]
   [5 0 5]]

  [[9 3 0]
   [4 6 8]
   [0 5 7]]

  [[3 0 9]
   [6 8 2]
   [5 7 4]]

  [[0 9 7]
   [8 2 9]
   [7 4 4]]

  [[9 7 7]
   [2 9 8]
   [4 4 8]]

  [[7 7 1]
   [9 8 4]
   [4 8 8]]]


 [[[6 9 4]
   [2 3 5]
   [3 6 1]]

  [[9 4 4]
   [3 5 0]
   [6 1 5]]

  [[4 4 6]
   [5 0 5]
   [1 5 4]]

  [[4 6 8]
   [0 5 7]
   [5 4 5]]

  [[6 8 2]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [ ]:
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __eq__(self, other):
        return np.array_equal(self, other) or np.array_equal(self, other.T)

    def __ne__(self, other):
        return not self.__eq__(other)
Z = SymmetricArray(np.random.rand(5,5))
print(Z)

[[0.66587683 0.30051533 0.2935543  0.3636827  0.85589498]
 [0.61918193 0.72008615 0.71597531 0.42568033 0.22515631]
 [0.42704861 0.34499864 0.949895   0.82929033 0.65495331]
 [0.01138912 0.36510324 0.36684737 0.93081792 0.25498541]
 [0.12353485 0.89321556 0.74012307 0.91952195 0.32532094]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)
result = np.einsum('ijk,ikl->jl', matrices, vectors)
print(result)

[[2.24075226]
 [3.36785161]
 [2.47003854]
 [2.42097925]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
a = np.ones((16,16))
k = 4
sum = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
board = np.zeros((16, 16), dtype = int)
def next_generation(board):
    # create a new board to store the next generation
    new_board = np.zeros(board.shape, dtype=int)

    # loop over every cell in the board
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            # count the number of live neighbors for this cell
            num_neighbors = np.sum(board[max(0, i-1):min(i+2, board.shape[0]), max(0, j-1):min(j+2, board.shape[1])]) - board[i, j]

            # apply the rules of the game to determine the state of the cell in the next generation
            if board[i, j] == 1 and (num_neighbors == 2 or num_neighbors == 3):
                new_board[i, j] = 1
            elif board[i, j] == 0 and num_neighbors == 3:
                new_board[i, j] = 1

    return new_board
for i in range(10):
    board = next_generation(board)

89. How to get the n largest values of an array (★★★)

In [ ]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print (a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5])
v3 = np.array([6, 7, 8])
grid = np.meshgrid(v1, v2, v3, indexing='ij')
cartesian_product = np.stack(grid, axis=-1).reshape(-1, len(grid))

print(cartesian_product)

[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


91. How to create a record array from a regular array? (★★★)

In [ ]:
a = np.array([1, 2, 3])
b = np.array(['a', 'b', 'c'])
c = np.array([0.1, 0.2, 0.3])

rec = np.rec.fromarrays([a, b, c], names='field1,field2,field3')

print(rec)

[(1, 'a', 0.1) (2, 'b', 0.2) (3, 'c', 0.3)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
Z = np.random.rand(int(5e5))
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z, Z, Z)

40.7 ms ± 998 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5.07 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.38 ms ± 54.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 10, size=(2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
A = np.array([[1, 2, 3],
              [2, 2, 3],
              [4, 5, 6],
              [7, 7, 7],
              [8, 9, 9],
              [8, 8, 8],
              [2, 2, 2],
              [3, 3, 3],
              [1, 1, 1],
              [4, 4, 4]])

unique_rows = np.unique(A, axis=1)
unequal_rows = A[np.where(np.apply_along_axis(len, 1, unique_rows) != 1)]

print(unique_rows)

[[1 2 3]
 [2 2 3]
 [4 5 6]
 [7 7 7]
 [8 9 9]
 [8 8 8]
 [2 2 2]
 [3 3 3]
 [1 1 1]
 [4 4 4]]


95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0, 10, 20)
B = np.random.uniform(0, 10, 20)
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[2.85970084e+00, 1.04894580e-01, 1.83550827e+00, 2.82601545e+00,
        1.21758612e+00, 2.05307756e-01, 2.08225471e+00, 2.65332556e+00,
        1.11780940e+00, 2.66809034e+00, 3.79338167e-01, 2.03893226e+00,
        2.25089518e+00, 5.33422237e-02, 4.73886886e-01, 2.26167475e+00,
        7.33217208e-01, 5.25034634e-01, 2.77535905e+00, 1.18919046e+00],
       [6.06811824e+01, 2.22580175e+00, 3.89484138e+01, 5.99663981e+01,
        2.58364666e+01, 4.35651073e+00, 4.41842294e+01, 5.63020194e+01,
        2.37192629e+01, 5.66153193e+01, 8.04933444e+00, 4.32649523e+01,
        4.77626817e+01, 1.13189084e+00, 1.00556031e+01, 4.79914178e+01,
        1.55584411e+01, 1.11409284e+01, 5.88914987e+01, 2.52339274e+01],
       [3.26268309e+01, 1.19676075e+00, 2.09416373e+01, 3.22425083e+01,
        1.38916546e+01, 2.34239237e+00, 2.37568109e+01, 3.02722589e+01,
        1.27532845e+01, 3.04407128e+01, 4.32793599e+00, 2.32625375e+01,
        2.56808598e+01, 6.08590829e-01, 5.40665898e+00, 2.5803

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
import numpy as np
X = np.random.rand(100)
Y = np.random.rand(100)

path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
path_length = np.insert(path_length, 0, 0)

num_samples = 20

samples = np.linspace(0, path_length[-1], num_samples)

x_samples = np.interp(samples, path_length, X)
y_samples = np.interp(samples, path_length, Y)

print(np.column_stack((x_samples, y_samples)))

[[0.02188749 0.17760236]
 [0.75604919 0.04046736]
 [0.37564432 0.45765763]
 [0.42037893 0.36171712]
 [0.40739604 0.05165135]
 [0.65619469 0.11251789]
 [0.81189443 0.33985276]
 [0.71417423 0.82339902]
 [0.4768451  0.75507645]
 [0.7718541  0.39485653]
 [0.49726596 0.50611885]
 [0.46138973 0.69634542]
 [0.82354474 0.18596892]
 [0.78509729 0.50196902]
 [0.36456804 0.73566536]
 [0.76079738 0.54147775]
 [0.66342647 0.83951258]
 [0.24729853 0.74134805]
 [0.6708716  0.20029378]
 [0.03834031 0.32158424]]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.32757408  0.04103696]
